{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "mywebapp.labels" . | nindent 4 }}
  name: {{ include "mywebapp.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "mywebapp.fullname" . }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}