{{/*
Generate data
*/}}
{{- $authDetails := dict "username" .Values.registryUsername "password" .Values.registryPassword }}
{{- $authDetails := set $authDetails "auth" (printf "%s:%s" .Values.registryUsername .Values.registryPassword | b64enc) }}
{{- $registryURL := "" }}
{{- $registryDetails := dict .Values.registryURL $authDetails }}
{{- $dockerConfig := dict "auths" $registryDetails }}

{{/*
Template
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mywebapp.fullname" . }}-image-pull-secret
  labels:
    {{- include "mywebapp.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ $dockerConfig | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
